{% set version = "2.0.1" %}

package:
  name: orderedset
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/o/orderedset/orderedset-{{ version }}.tar.gz
  sha256: ee942c5bebd06d64bfa1d25ed0c40ae5fc9ee8d3d4c6ca9c73fd7a11321ec484

build:
  number: 0
  script: python -m pip install --no-deps .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - orderedset

about:
  home: https://github.com/simonpercivall/orderedset
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'An Ordered Set implementation in Cython.'

extra:
  recipe-maintainers:
    - ocefpaf
