travis:
  secure:
    BINSTAR_TOKEN: NqAWaHUcpKC4NLYbuZWLZLwjvG9ugY26NeK9Ezz/dOz6HNaXYFiPV+Nf98QYCRzx5Mq6xvyrIQcqiOEaNtnZoKO5ZdA3LGvoCN/YWClqa5Mdr5w59m33LTRt1Wwrkp0PLNBzYcVHdvJDo3pmx1paWgLZyIDWy0EGLMXk3wXxKN3kYz5jrTqO/RcDftfq9BY44kkfYoViFzf0mzw4Ulh33JcPGGaXsYn0iaeP8qD3uKe1HOT85rRfb0/kRlGf0U0Giw63PkZ54Bq1VG7UkomhWOgTj1EVtSPJXnbVsU8OxnGNxK8L96kgz2TF8qgjF132I4GRDK8JycEnKUmCstdZzzRBt618qJzkTCUC4sXnEny9HsxWPvyMjs00LWTG7So9h5kNF1RFVrd3DeUOn/uS5bLoidi1w9HIm/2XTDJNpnlsBmr5xBQ3Oxvrel+JoWVzetrhxwXQrggTkvDl6a4BU/Xf+/Wxv+CbqLITKZwrbGKi6SB1pqS4LyLr2nvPR7EZc8ayf29qYOkEe2NWMZnkMGsdmgO/vegs3PbnCEdVoyJhg3BpVfhn2BJnQJlAQ2oifle+fElXC9X6GxiYsGgu/T97lIxVw+G17hsL+TsNvtEF70zAeyPIbhcn0YmGUkD4gvGWo4V0o8YzOA6XlGmbf73/Rt9qFMuPtJp1IP8gk3s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
