travis:
  secure:
    BINSTAR_TOKEN: CbKLDBTqrSgm43jlJM/wXqtAR8paRcMQ8cOlNXaHAFR9c39Fp/xYTy1VHmHmIGbUKYpuWCJB9QGLGDfo1dj+a1zoywgPBiS8DtI+180f4KiPxN9WeVPEWv30yzz16f6kNOguI3PXNtM2bMJF9cRxGWUhUZGexHEha01Q7aCt2vXu2DvanVUDsDFYWv1+kp5Q62JDR7HJ+OLOc5euRAA52It3tALeii/UUa/q7lMXYIuYLt3reIbeM7pcBzEzmZ9vXD+MLCbIK9yg/U87cutKWzu2oPNkWurab4ZUjC42knndXTJULqKJAW6PtioSQVViQsF/bOT8NIVoO04yJ7bwFm2+sNFivkGB2gw6v7z0Qm5wsFcYWuwKz5imUqaMg98K4tH6sabIk+An5GB/24b6hVrpwZy1GnjBzO637xDNpHe59fXaRFrIXYEDZnjIlVI55K1hPkL/tzuhIPsgEgCWXwgNsAl62C2uC9pFivdsC4A0yy8/73nbFYagSsbOb+3d4MnOpMvtWV0gWFA0Wk9AiGwKvrVGr8y6DPv/Xn52/de270lPxuWXGFRJzlIBalv8PMLkKTs+Tjhjav7AeQJ39T1gxaCkz1Aq+Di4BPZN2eI5vSfEl0KD3w+xCO8CCI/suZzYz7Hj/w/ikqNJwCXHUa8kLYCzC90vhERnl2WhyMs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
