travis:
  secure:
    BINSTAR_TOKEN: AwQ73NuTyfGOfS03qc28MVHOOIbiz4Uy5pk07Cqg/9K7/uznOH12FJkLnwmPKQaSlMB4ei998eVxm3LYQnGGurNJ3dbVXj4LBBqfif7l2iDfkoW2W/nA0uTR+gp2P+xuvrp2Xl9KCTd9FmSUAnP9hJ+2RqUZOzNAQOmlzdIIN1vHNIkLvrZh7yGSjOX2V2hwsraWJrwA8IDcRFVMbPjlgDpQu8m+zZN6Ksp5enXQuEkyC/HuBLDB7I5rQqVlh+j6o6rQP+NHWFCMZBX90vNYGu6hUcnuwtIk3vF/q/pvBTfcVKU+bVmw3IcB65PQLGdFDKrgA7D41JXZNyEm+BQnUmhJfQyfo9wv8PbG7bqCHY773zBANXv4l0Xt0sZfojmIrQaoxcb00o+CaTk9A48eeode57LIMJfar3ndz6VdgKsa2drnq7TxSqADaIXcgZtQrmx5wE2gSMhBqNQSuY7nqtkiwPNYYZDFnRZztBD19kVsSnDACV5ow1kiEzU8b+cK618Slk768xm5h3NHQZaPDkYlM7lcdiAN4FaWmULNqAh57BjTzGxGS/OB8vDRkOqvLMjrEH9OXia/OiNUCo3XShVKs+UcA1SypfFswcHRYKtiflspDlcPaxlAT8FcpSWoJWhQNs+VpoI2av/IoAEmPYr4O4xVPTasMg1Y8yDP18o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
